{% set name = "seapipy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seapipy-{{ version }}.tar.gz
  sha256: e47a7f0af10e487da3af71849d8c7677b19f7cc76d9cbb7b15ece447bc3bd058

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 
    - setuptools
  run:
    - python >=3.9, <3.11
    - matplotlib-base >=3.6.2
    - numpy >=1.23.4
    - scipy >=1.9.3
    - tomli

test:
  imports:
    - seapipy
  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/borgesaugusto/seapipy
  summary: API for creating Surface Evolver files with python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE 

extra:
  recipe-maintainers:
    - borgesaugusto
